name: Build Container

on: [push]

jobs:
  build-llvm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build llvm xtensa
      run: docker build . --file Dockerfile.llvm-build --tag llvm-xtensa:${{ github.sha }}
  # build:
  #   needs: build-llvm
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the image
  #     run: docker build . --file Dockerfile --tag rust-esp:${{ github.sha }}

